version: '3'

services:
  scrapers-ca:
    build: .
    volumes:
      - "../:/src/scrapers-ca"
    ports:
      - "80"
    working_dir: /src
    restart: always
    command: "tail -f /dev/null"

volumes:
  scrapers-ca:
