version: '3'

services:
  scrapers-ca:
    build: .
    volumes:
      - "../:/src/scrapers-ca"
    ports:
      - "80"
    working_dir: /src/scrapers-ca
    restart: always
    command: "tail -f /dev/null"
